<?xml version="1.0"?>
<!DOCTYPE BusinessCard SYSTEM "businesscard.dtd">
<!-- <!DOCTYPE BusinessCard [
<!ELEMENT BusinessCard (Name, phone+, email?)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type (mobile | fax | work | home) #REQUIRED>
<!ELEMENT email (#PCDATA)>
]> -->
<BusinessCard>
	<Name>Joe Marini</Name>
	<phone type="mobile">(415) 555-4567</phone>
	<phone type="work">(800) 555-9876</phone>
	<phone type="fax">(510) 555-1234</phone>
	<phone type="home">(425) 555-8989</phone>
	<email>joe@joe.com</email>
</BusinessCard>
